### ISSUE TITLE
Textboxes?

### ISSUE THREAD

**Issue by freemin7** [wookay/Poptart.jl#11]
This library doesn't seem to provide text boxes. ImGui provides them in theory. Could they be added?

**Comment by wookay** [comment]
it doesn't work now. it needs to some rework based on CImGui examples.

**Comment by wookay** [comment]
update to Poptart 0.3.1

**Comment by freemin7** [comment]
Thank you, is there an example where the text from the box is used?

**Comment by wookay** [comment]
look at https://github.com/wookay/Poptart.jl/blob/master/examples/inputs.jl

**Comment by freemin7** [comment]
I was aware of that example, but that doesn't tell me how to get the text from the text field.

**Comment by wookay** [comment]
```julia
input1 = InputText(label="Subject", buf="")
println(input1.buf)
```

see also api https://wookay.github.io/docs/Poptart.jl/Desktop/#Poptart.Desktop.InputText

**Comment by freemin7** [comment]
Thanks
